# Site settings
title: lilbuds stuff
email: ""
description: "The (hopefully) final site to host my various musings"
url: "https://lilbud.github.io"
#baseurl: ""
#facebook_username: ""
#twitter_username: ""
#instagram_username: ""
github_username:  "lilbud"
#deviantart_username: ""
#flickr_username: ""
#discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   lilbud
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Internal nav
nav:
  - GRAPHICS: "https://lilbud.github.io/graphics/"  
  - JOURNAL: "https://lilbud.github.io/journal/"  
  - ABOUT: "https://lilbud.github.io/about/" 

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000

# Build settings
markdown: kramdown
highlighter: rouge
#permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
  